#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODESPACES_DIR="$ROOT_DIR/.codespaces"
RUNTIME_ENV_FILE="$CODESPACES_DIR/runtime_env.sh"

mkdir -p "$CODESPACES_DIR"

ENV_KEYS=(
  MONGO_URI
  REDIS_URL
  JWT_SECRET
  ENCRYPTION_KEY
  WEBHOOK_SECRET
  WEBHOOK_URL
  BACKEND_URL
  FRONTEND_URL
  JULES_API_URL
  JULES_API_KEY
  GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET
  GOOGLE_REDIRECT_URI
  GEMINI_API_KEY
  OPENAI_API_KEY
  ANTHROPIC_API_KEY
  YOUTUBE_DATA_API_KEY
  PEXELS_API_KEY
  PIXABAY_API_KEY
  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
  RAZORPAY_KEY_ID
  RAZORPAY_KEY_SECRET
  RAZORPAY_WEBHOOK_SECRET
  TELEGRAM_BOT_TOKEN
  TELEGRAM_ALLOWED_CHAT_ID
  PIPELINE_RUNNER
  PIPELINE_PYTHON_CMD
  AZURE_JOB_NAME
  AZURE_RESOURCE_GROUP
  AZURE_SUBSCRIPTION_ID
  AZURE_TENANT_ID
  AZURE_CLIENT_ID
  AZURE_CLIENT_SECRET
)

REQUIRED_KEYS=(
  MONGO_URI
  REDIS_URL
  JWT_SECRET
  ENCRYPTION_KEY
  WEBHOOK_SECRET
  WEBHOOK_URL
  BACKEND_URL
)

{
  echo "#!/usr/bin/env bash"
  echo "# Auto-generated by scripts/bootstrap_codespaces_env.sh"
  echo "export PYTHONPATH=\"${PYTHONPATH:-$ROOT_DIR/pipeline/src}\""
  echo "export PIPELINE_RUNNER=\"${PIPELINE_RUNNER:-local}\""
  echo "export PIPELINE_PYTHON_CMD=\"${PIPELINE_PYTHON_CMD:-python}\""
  for key in "${ENV_KEYS[@]}"; do
    value="${!key-}"
    if [[ -n "$value" ]]; then
      printf 'export %s=%q\n' "$key" "$value"
    fi
  done
} > "$RUNTIME_ENV_FILE"

chmod 700 "$RUNTIME_ENV_FILE"

MISSING=()
for key in "${REQUIRED_KEYS[@]}"; do
  value="${!key-}"
  if [[ -z "$value" ]]; then
    MISSING+=("$key")
  fi
done

BASHRC="${HOME}/.bashrc"
ZSHRC="${HOME}/.zshrc"
HOOK_MARKER="# codex-codespaces-runtime-env"
HOOK_LINE="source \"$RUNTIME_ENV_FILE\""

for shell_rc in "$BASHRC" "$ZSHRC"; do
  if [[ -f "$shell_rc" ]]; then
    if ! grep -Fq "$HOOK_MARKER" "$shell_rc"; then
      {
        echo ""
        echo "$HOOK_MARKER"
        echo "$HOOK_LINE"
      } >> "$shell_rc"
    fi
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "[codespaces-env] Generated $RUNTIME_ENV_FILE"
  echo "[codespaces-env] Missing recommended secrets: ${MISSING[*]}"
  echo "[codespaces-env] Add them in: GitHub repo -> Settings -> Secrets and variables -> Codespaces"
else
  echo "[codespaces-env] Generated $RUNTIME_ENV_FILE with required keys."
fi

